### ISSUE TITLE
Automatic adjustments via Storyboards?

### ISSUE THREAD

**Issue by nickoneill** [lionheart/KeyboardAdjuster#1]
This seems like a great way to tackle keyboard-adjustments to views, though I'm betting you're mostly generating the elements you want to move around in code.

I do a lot of view setup in storyboards and I attach bottom-view stuff to the bottom layout guide. I'm not real familiar with messing with layout guides in code but I'm wondering if there's some automation that could adjust the bottom layout guide without having to remove and reset it in `viewDidLoad`. I'll look more into this when I have some time, but thoughts?

**Comment by dlo** [comment]
@nickoneill Sorry about the delay, you've probably long forgotten about this, but if you're curious how to do this in the future (and for anyone else stumbling here from Google or issues search), check out my comment at https://github.com/lionheart/KeyboardAdjuster/issues/5#issuecomment-348360685 for an example for how to set this all up using IB. 🍻
