### ISSUE TITLE
UIKeyboardWillShow not UIKeyboardDidShow

### ISSUE THREAD

**Issue by johnmci** [lionheart/KeyboardAdjuster#4]
you setup 
NSNotification.Name.UIKeyboardWillHide
NSNotification.Name.UIKeyboardWillShow

but then take down 
       notificationCenter.removeObserver(self, name: NSNotification.Name.UIKeyboardWillHide, object: nil)
        notificationCenter.removeObserver(self, name: NSNotification.Name.UIKeyboardDidShow, object: nil)

I am sure you mean to do  WILLSHOW not DIDSHOW

        notificationCenter.removeObserver(self, name: NSNotification.Name.UIKeyboardWillShow NSNotification.Name.UIKeyboardWillShow, object: nil)

**Comment by dlo** [comment]
@johnmci Thanks for the report. You're correct, this change was made in a PR. Happy to merge in an edit to the README and sample code.

**Comment by johnmci** [comment]
Dan, sorry that didn't fix the issue. Busy with a customer app chasing a
keyboard issue in a Eureka tableview, and noticed your keyboard logic
firing.
However it still fires.

Although we do

    public func deactivateKeyboardAdjuster() {
    let notificationCenter = NotificationCenter.default
    notificationCenter.removeObserver(self, name:
    NSNotification.Name.UIKeyboardWillHide, object: nil)
    notificationCenter.removeObserver(self, name:
    NSNotification.Name.UIKeyboardWillShow, object: nil) // FIX
    }

That does not actually unregister the observer because you are using the
 addObserver using a block pattern.

notificationCenter.addObserver(forName:
NSNotification.Name.UIKeyboardWillShow, object: nil, queue:
OperationQueue.main, using: {
[weak self] notification in

self?.keyboardWillShow(notification)

showBlock?()
})

Apple says to unregister observations, you pass the object returned by this
method to removeObserver(_:). You must invoke removeObserver(_:) or
removeObserver(_:name:object:) before any object specified by
addObserverForName:object:queue:usingBlock: is deallocated.


On Sun, Apr 30, 2017 at 1:26 PM, Dan Loewenherz <notifications@github.com>
wrote:
>
> @johnmci Thanks for the report. You're correct, this change was made in a
PR. Happy to merge in an edit to the README and sample code.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.




--
===========================================================================
John M. McIntosh. Corporate Smalltalk Consulting Ltd
https://www.linkedin.com/in/smalltalk
===========================================================================

**Comment by dlo** [comment]
@johnmci Fixed in https://github.com/lionheart/KeyboardAdjuster/commit/a398f392f4c3cef82e3420c66e5530c7147bf48c. Apologies about the delay here.
